config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from debug_toolbar import urls as debug_toolbar_urls
from rest_framework import routers

from cities.api.viewsets import CityViewSet, CountryViewSet, StateViewSet
from publishers.api.viewsets import GroupViewSet
from reports.api.viewsets import MFSViewSet
from system.views import home, login, logout

router = routers.DefaultRouter()
router.register(r'countries', CountryViewSet)
router.register(r'states', StateViewSet)
router.register(r'cities', CityViewSet)
router.register(r'groups', GroupViewSet)
router.register(r'mfs', MFSViewSet)

urlpatterns = [
    path('api/', include(router.urls)),

    path('accounts/', include('django.contrib.auth.urls')),
    path('mailing/', include('mailing.urls')),
    path('pioneering/', include('pioneering.urls')),
    path('publishers/', include('publishers.urls')),
    path('reports/', include('reports.urls')),
    path('servants/', include('servants.urls')),
    path('login/', login, name='system-login'),
    path('logout/', logout, name='system-logout'),
    path('', include('system.urls')),
    path('', home, name='home'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include(debug_toolbar_urls))
    ]

congregationms/mailing/urls.py
from django.urls import path

from .views import MailCreateView

app_name = 'mailing'
urlpatterns = [
    path('new/<str:publisher>', MailCreateView.as_view(), name='new'),
]

congregationms/reports/urls.py
from django.urls import path

from .views import (
    InfirmedListView, MFSCreate, MFSDelete, MFSDetail, MFSList, MFSUpdate,
    MFSHistoryList, PioneerListView, sample_mfs, ServantListView,
    ShareToRedirectView, InactivePublisherListView, AssetListView
)

app_name = 'reports'
urlpatterns = [
    path('monthly-field-service/', MFSList.as_view(), name='mfs-index'),
    path('monthly-field-service/history/publisher/<slug:publisher>/',
         MFSHistoryList.as_view(), {'view_type': 'publisher'},
         name='mfs-history'),
    path('monthly-field-service/history/group/<str:group>/',
         MFSHistoryList.as_view(), {'view_type': 'group'},
         name='mfs-history-group'),
    path('monthly-field-service/delete/<str:pk>/',
         MFSDelete.as_view(), name='mfs-delete'),
    path('monthly-field-service/new/', MFSCreate.as_view(), name='mfs-create'),
    path('monthly-field-service/<str:pk>/',
         MFSDetail.as_view(), name='mfs-detail'),
    path('monthly-field-service/update/<str:pk>/',
         MFSUpdate.as_view(), name='mfs-update'),


    path('mfs/download/group/<str:pk>/', sample_mfs, name='mfs-download'),
    path('mfs/<str:publisher>/share-to/',
         ShareToRedirectView.as_view(), name='share_to'),

    path(
        'publishers/inactive/',
        InactivePublisherListView.as_view(),
        name='publishers_inactive'),
    path(
        'publishers/assets/',
        AssetListView.as_view(),
        name='publishers_assets'
    ),
    path(
        'publishers/<str:view_type>/',
        InfirmedListView.as_view(),
        name='publishers'),

    path(
        'pioneering/<str:view_type>/',
        PioneerListView.as_view(),
        name='pioneering'),

    path(
        'servants/<str:view_type>/',
        ServantListView.as_view(),
        name='servants'),
]

congregationms/servants/urls.py
from django.urls import path

from .views import ServantCreateView, ServantDetailView, ServantUpdateView, ServantListView


app_name = 'servants'
urlpatterns = [
    path('', ServantListView.as_view(), name='index'),
    path('new/', ServantCreateView.as_view(), name='create'),
    path('delete/<str:pk>/', ServantDetailView.as_view(), name='delete'),
    path('detail/<str:pk>/', ServantDetailView.as_view(), name='detail'),
    path('update/<str:pk>/', ServantUpdateView.as_view(), name='update'),
]

congregationms/system/urls.py
from django.urls import path

from .views import dashboard, AccountView

app_name = 'system'
urlpatterns = [
    path('dashboard', dashboard, name='dashboard'),
    path('account/', AccountView.as_view(), name='account'),
]

congregationms/urls.py
from django.contrib import admin
from django.urls import path

from system.views import home

urlpatterns = [
    path('', home, name='home'),
    path('admin/', admin.site.urls),
]

congregationms/pioneering/forms.py
from django.forms import ModelForm
from django.forms.models import inlineformset_factory

from .models import Pioneer, PioneerDetail
from publishers.utils import get_publishers_as_choices


class PioneerModelForm(ModelForm):
    class Meta:
        model = Pioneer
        fields = [
            'publisher', 'code'
        ]

    def __init__(self, *args, **kwargs):
        request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)

        publishers = []
        if request:
            # get publishers as choices
            publishers = get_publishers_as_choices(request=request)
        self.fields['publisher'].choices = publishers


class PioneerDetailModelForm(ModelForm):

    class Meta:
        model = PioneerDetail
        fields = [
            'pioneer',
            'pioneer_type',
            'date_start',
            'date_end',
        ]


PioneerDetailFormSet = inlineformset_factory(
    Pioneer,
    PioneerDetail,
    form=PioneerDetailModelForm,
    fields=[
        'pioneer',
        'pioneer_type',
        'date_start',
        'date_end'],
    extra=1,
    can_delete=True
)

congregationms/cities/views.py
from django.shortcuts import render

# Create your views here.

congregationms/mailing/views.py
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import reverse
from django.views.generic.edit import CreateView

from .forms import MailModelForm
from .models import Mail


class MailCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    """Receive query params [filename]."""
    form_class = MailModelForm
    model = Mail
    permission_required = ('mailing.add_mail',)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_initial(self):
        initial = super().get_initial()
        initial = initial.copy()
        initial['attachment'] = self.request.GET.get('filename')
        return initial

    def get_success_url(self, *args, **kwargs):
        return reverse('publishers:index')

    def form_valid(self, form):
        _value = super().form_valid(form)

        if form.send_email():
            messages.success(
                self.request,
                'Successfully shared via email!')
        else:
            message = 'Something went wrong. Unable to share via \
                        email. Please check your internet connection.'
            messages.error(self.request, message)
            return HttpResponseRedirect(self.request.GET.get('on_fail'))
        return _value

congregationms/pioneering/views.py
from django.contrib import messages
from django.db import transaction
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .forms import PioneerDetailFormSet, PioneerModelForm
from .models import Pioneer
from publishers.utils import get_user_groups_members
from system.utils import (
    LoginAndPermissionRequiredMixin, AddUserToFormMixin, AddRequestToForm)


class PioneerListView(LoginAndPermissionRequiredMixin, ListView):
    model = Pioneer
    context_object_name = 'pioneers'
    permission_required = ('pioneering.view_pioneer',)

    def get_queryset(self):
        auth_pubs = self.request.authorized_publisher_pks
        if auth_pubs:
            queryset = Pioneer.objects.filter(publisher__in=auth_pubs)
            queryset = queryset.select_related('publisher')
        else:
            queryset = self.model.objects.none()

        return queryset


class PioneerDetailView(LoginAndPermissionRequiredMixin, DetailView):
    model = Pioneer
    context_object_name = 'pioneer'
    slug_field = 'code'
    permission_required = ('pioneering.view_pioneer',)

    def get_queryset(self):
        q = super().get_queryset()
        q = q.prefetch_related('details', 'publisher')
        return q


class PioneerCreateView(
        AddRequestToForm, LoginAndPermissionRequiredMixin, CreateView):
    model = Pioneer
    form_class = PioneerModelForm
    permission_required = ('pioneering.add_pioneer',)

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data['details'] = PioneerDetailFormSet(self.request.POST)
        else:
            data['details'] = PioneerDetailFormSet()

        return data

    def form_valid(self, form):
        context = self.get_context_data()
        details = context['details']

        with transaction.atomic():
            if details.is_valid():
                self.object = form.save()
                details.instance = self.object
                details.save()

        messages.success(
            self.request,
            'Successfully created new pioneer. Continue editing other details'
        )
        return super().form_valid(form)

    def get_success_url(self, *args, **kwargs):
        return reverse('pioneering:update', args=[str(self.object.code)])


class PioneerUpdateView(
        AddRequestToForm, LoginAndPermissionRequiredMixin, UpdateView):
    model = Pioneer
    form_class = PioneerModelForm
    context_object_name = 'pioneer'
    slug_field = 'code'
    permission_required = ('pioneering.change_pioneer',)

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data['details'] = PioneerDetailFormSet(
                self.request.POST, instance=self.object)
        else:
            data['details'] = PioneerDetailFormSet(instance=self.object)
        data['is_active'] = self.object.is_active
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        details = context['details']

        with transaction.atomic():
            if details.is_valid():
                details.instance = self.object
                details.save()
                self.object = form.save()

        messages.success(
            self.request,
            'Successfully updated.'
        )
        return super().form_valid(form)


class PioneerDeleteView(LoginAndPermissionRequiredMixin, DeleteView):
    model = Pioneer
    success_url = reverse_lazy('pioneering:index')
    permission_required = ('pioneering.delete_pioneer',)

    def get_success_url(self):
        messages.success(
            self.request,
            'Successfully deleted {}.'.format(str(self.object))
        )
        return super().get_success_url()

congregationms/publishers/views.py
#from django.shortcuts import render
from django.contrib import messages
from django.db import transaction
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .forms import GroupModelForm, GroupMemberFormSet, PublisherModelForm
from .models import Group, Publisher, Member
from .utils import get_publishers_as_choices
from system.utils import LoginAndPermissionRequiredMixin


# Create your views here.
class PublisherList(LoginAndPermissionRequiredMixin, ListView):
    model = Publisher
    permission_required = 'publishers.view_publisher',

    def get_queryset(self):
        auth_pubs = self.request.authorized_publisher_pks
        if auth_pubs:
            queryset = Publisher.objects.filter(id__in=auth_pubs)
        else:
            queryset = self.model.objects.none()

        return queryset


class PublisherUpdate(LoginAndPermissionRequiredMixin, UpdateView):
    model = Publisher
    form_class = PublisherModelForm
    context_object_name = 'publisher'
    permission_required = 'publishers.change_publisher',

    def get_queryset(self, **kwargs):
        queryset = super().get_queryset(**kwargs)
        queryset = queryset.select_related('city', 'city__state')

        return queryset

    def form_valid(self, form):
        messages.success(
            self.request,
            'Successfully updated.'
        )
        return super().form_valid(form)


class PublisherDetail(LoginAndPermissionRequiredMixin, DetailView):
    model = Publisher
    context_object_name = 'publisher'
    permission_required = 'publishers.view_publisher',

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        contact_numbers = self.object.contact_numbers
        contact_numbers = contact_numbers.split(',')
        contact_numbers = ', '.join(contact_numbers)

        context['contact_numbers'] = contact_numbers
        return context

    def get_queryset(self, **kwargs):
        queryset = super().get_queryset(**kwargs)
        queryset = queryset.select_related(
            'city', 'city__state', 'city__state__country')

        return queryset


class PublisherCreate(LoginAndPermissionRequiredMixin, CreateView):
    model = Publisher
    form_class = PublisherModelForm
    permission_required = 'publishers.add_publisher',

    def form_valid(self, form):
        messages.success(
            self.request,
            'Successfully created new publisher. Continue editing other details'
        )
        return super().form_valid(form)

    def get_success_url(self, *args, **kwargs):
        return reverse('publishers:update', args=[str(self.object.slug)])


class PublisherDelete(LoginAndPermissionRequiredMixin, DeleteView):
    model = Publisher
    success_url = reverse_lazy('publishers:index')
    permission_required = 'publishers.delete_publisher',

    def get_success_url(self):
        messages.success(
            self.request,
            'Successfully deleted {}.'.format(str(self.object))
        )
        return super().get_success_url()


class GroupList(LoginAndPermissionRequiredMixin, ListView):
    model = Group
    permission_required = 'publishers.view_group',

    def get_queryset(self):
        queryset = self.model.objects.none()

        # user = self.request.user
        # publisher = user.publisher
        # group = publisher.group_members.filter(is_active=True)
        # group = group.first()  # publishers.Member object
        # if group:
        #     queryset = super().get_queryset()
        #     queryset = queryset.filter(id=group.group_id)
        groups = self.request.authorized_groups  # publisher.UserGroup objects
        if groups:
            groups = [g.group_id for g in groups]  # Group pks
            queryset = super().get_queryset().filter(id__in=groups)
            queryset = queryset.select_related('congregation')

        return queryset


class GroupDetail(LoginAndPermissionRequiredMixin, DetailView):
    model = Group
    context_object_name = 'group'
    permission_required = 'publishers.view_group',


class GroupUpdate(LoginAndPermissionRequiredMixin, UpdateView):
    model = Group
    form_class = GroupModelForm
    context_object_name = 'group'
    permission_required = 'publishers.change_group',

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            formset = GroupMemberFormSet(
                self.request.POST, instance=self.object)
        else:
            formset = GroupMemberFormSet(instance=self.object)

        data['members'] = formset
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        members = context['members']

        with transaction.atomic():
            self.object = form.save()
            if members.is_valid():
                members.instance = self.object
                members.save()

        messages.success(
            self.request,
            'Successfully edited Group {}.'.format(str(self.object))
        )
        return super().form_valid(form)


class GroupDelete(LoginAndPermissionRequiredMixin, DeleteView):
    model = Group
    success_url = reverse_lazy('publishers:group-index')
    permission_required = 'publishers.delete_group',

    def get_success_url(self):
        messages.success(
            self.request,
            'Successfully deleted {}.'.format(str(self.object))
        )
        return super().get_success_url()


class GroupCreate(LoginAndPermissionRequiredMixin, CreateView):
    model = Group
    form_class = GroupModelForm
    permission_required = 'publishers.add_group',

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            formset = GroupMemberFormSet(self.request.POST)
        else:
            formset = GroupMemberFormSet()

        data['members'] = formset

        return data

    def form_valid(self, form):
        context = self.get_context_data()
        members = context['members']

        with transaction.atomic():
            self.object = form.save()
            if members.is_valid():
                members.instance = self.object
                members.save()

        messages.success(
            self.request,
            'Successfully created new Group {}.'.format(str(self.object))
        )
        return super().form_valid(form)

congregationms/templates/servants/base.html
{% extends "base.html" %}


{% block breadcrumbs %}
  <li><a href='{% url "servants:index" %}'>Servants</a></li>
  {% block subbreadcrumbs %}{% endblock subbreadcrumbs %}
{% endblock breadcrumbs %}

{% block navbaritems %}
  {% include "_snippets/navbar_items.html" with servants_active='is-active' %}
{% endblock navbaritems %}

{% block aside_menu %}
  {% include "aside.html" with servants_active='is-active' %}  
{% endblock aside_menu %}

congregationms/templates/servants/servant_detail.html
{% extends "servants/base.html" %}
{% load static %}

{% block title %}
  <title>Servant Detail | {{object.publisher.name|title}}</title>
{% endblock title %}

{% block subbreadcrumbs %}
  <li class="is-active"><a href='#'>Detail</a></li>  
{% endblock subbreadcrumbs %}

{% block main %}
  <h1 class="title">Servant Detail</h1>

  <div class="field is-grouped is-pulled-right" id="delete-button-app">
    <div class="control">
      <form id="form--{{ object.pk }}" action='{% url "servants:delete" object.pk %}' method="POST" @submit.prevent="confirmDelete">
        {% csrf_token %}
        <button class="button is-outlined" type="submit" form="form--{{ object.pk }}" :disabled="disabled">{% include "_snippets/icon_trash.html" %}</button>
      </form>
    </div>

    <div class="control">
      <a href='{% url "servants:update" object.pk %}'><button class="button is-outlined">{% include "_snippets/icon_edit.html" %}</button></a>
    </div>
  </div>
  
  <p class="is-size-3">{{ object.publisher.name|upper }}</p>
  <p><a href='{% url "reports:mfs-history" object.publisher.slug %}'>View MFS history</a></p>
  <p>Elder: {% if object.elder %}{% include "_snippets/icon_check.html" %}{% else %}{% include "_snippets/icon_times.html" %}{% endif %}</p>
  <p>Ministerial Servant: {% if object.ms %}{% include "_snippets/icon_check.html" %}{% else %}{% include "_snippets/icon_times.html"  %}{% endif %}</p>
{% endblock main %}

{% block vueinstance %}
    <script src="{% static "deleteButtonApp.js" %}"></script>
{% endblock vueinstance %}

congregationms/templates/servants/servant_form.html
{% extends "servants/base.html" %}
{% load static %}

{% block title %}
    <title>{{mode}} Servant</title>  
{% endblock title %}

{% block subbreadcrumbs %}
    <li class="is-active"><a href='#'>{{mode}}</a></li>  
{% endblock subbreadcrumbs %}

{% block main %}
  {% if object %}
   <h1 class="title">Edit {{object}}</h1>  
  {% else %}
   <h1 class="title">Create new Servant</h1>  
  {% endif %}

    <form method="POST" id="form--servant-form">
      {% csrf_token %}
      <div class="field">
        <label class="label">{{form.publisher.label}}</label>
        <div class="control">
          <div class="select is-fullwidth">
            {{form.publisher}}
          </div>
        {{form.publisher.errors}}
        </div>
      </div>

      <div class="field">
        <label class="label">Type</label>
        <div class="control">
          <label class="radio">
            <input type="radio" name="sType" id="elder" v-model="servantType" value="elder">
            Elder
          </label>
          <label class="radio">
            <input type="radio" name="sType" id="ms" v-model="servantType" value="ms">
            MS
          </label>
          {{form.servant_type.errors}}
        </div>
      </div>
      <input type="hidden" name="servant_type" v-model="servantType" ref="servantType">
      <input type="hidden" name="elder" v-model="elder" ref="elder" data-default="{{form.elder.value}}">
      <input type="hidden" name="ms" v-model="ms" ref="ms" data-default="{{form.ms.value}}">

      {% if object %}
        {% include "_snippets/button_save.html" %}
      {% else %}
        {% include "_snippets/button_create.html" %}
      {% endif %}
    </form>
{% endblock main %}

{% block vueinstance %}
    <script>
      servantFormApp = new Vue({
        delimiters: ['[[', ']]'],

        el: '#form--servant-form',

        data: () => {
          return {
            servantType: '',
            elder: '',
            ms: '',
          }
        },

        methods: {
          setDefault: function () {
            this.elder = this.$refs.elder.getAttribute('data-default') == "True";
            this.ms = this.$refs.ms.getAttribute('data-default') == "True";
            if (this.elder) {
              this.servantType = 'elder'
            } else {
              if (this.ms) {
                this.servantType = 'ms'
              }
            }
          }
        },

        watch: {
          servantType: function (val, oldVal) {
            if (val == 'elder') {
              this.elder = true;
            } else {
              this.elder = false;
            }
            this.ms = !this.elder;
          }
        },

        mounted: function () {
          this.setDefault();
        }
      });
    </script>  
{% endblock vueinstance %}

congregationms/templates/servants/servant_list.html
{% extends "servants/base.html" %}

{% block title %}
  <title>Servants</title>  
{% endblock title %}

{% block main %}
  <h1 class="title">Servants List</h1>
  <a href='{% url "servants:create" %}'>{% include "_snippets/button_new.html" %}</a>

  <table class="table is-fullwidth">
    <thead>
      <tr>
        <th class="has-text-centered">Name</th>
        <th class="has-text-centered">Type</th>
        <th class="has-text-centered">Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for servant in object_list %}
        <tr>
          <td>{{ servant|title }}</td>
          <td>
            {% if servant.servant_type %}
              {{ servant.servant_type }}
            {% else %}
              {% include "_snippets/icon_times.html" %}
            {% endif %}
          </td>
          <td>
            <a href='{% url "servants:detail" servant.pk %}'><span class="button is-outlined">{% include "_snippets/icon_view.html" %}</span></a>
            <a href='{% url "servants:update" servant.pk %}'><span class="button is-outlined">{% include "_snippets/icon_edit.html" %}</span></a>
          </td>
        </tr>
      {% endfor %}

      {% if not object_list %}
        <tr>
          <td colspan="3" class="has-text-centered">No servants. Please <a href="{% url 'servants:create' %}"><u>add</u></a>.</td>
        </tr>  
      {% endif %}
    </tbody>
  </table>
{% endblock main %}