config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from debug_toolbar import urls as debug_toolbar_urls
from rest_framework import routers

from cities.api.viewsets import CityViewSet, CountryViewSet, StateViewSet
from publishers.api.viewsets import GroupViewSet
from reports.api.viewsets import MFSViewSet
from system.views import home, login, logout

router = routers.DefaultRouter()
router.register(r'countries', CountryViewSet)
router.register(r'states', StateViewSet)
router.register(r'cities', CityViewSet)
router.register(r'groups', GroupViewSet)
router.register(r'mfs', MFSViewSet)

urlpatterns = [
    path('api/', include(router.urls)),

    path('accounts/', include('django.contrib.auth.urls')),
    path('mailing/', include('mailing.urls')),
    path('pioneering/', include('pioneering.urls')),
    path('publishers/', include('publishers.urls')),
    path('reports/', include('reports.urls')),
    path('servants/', include('servants.urls')),
    path('login/', login, name='system-login'),
    path('logout/', logout, name='system-logout'),
    path('', include('system.urls')),
    path('', home, name='home'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include(debug_toolbar_urls))
    ]

congregationms/mailing/urls.py
from django.urls import path

from .views import MailCreateView

app_name = 'mailing'
urlpatterns = [
    path('new/<str:publisher>', MailCreateView.as_view(), name='new'),
]

congregationms/publishers/urls.py
from django.urls import path

from .views import (
    PublisherCreate, PublisherDelete, PublisherDetail,
    PublisherList, PublisherUpdate, GroupCreate, GroupDetail, GroupList, GroupUpdate
)


app_name = 'publishers'
urlpatterns = [
    path('', PublisherList.as_view(), name='index'),
    path('groups/', GroupList.as_view(), name='group-index'),
    path('groups/new/', GroupCreate.as_view(), name='group-create'),
    path('groups/detail/<str:pk>/', GroupDetail.as_view(), name='group-detail'),
    path('groups/edit/<str:pk>/', GroupUpdate.as_view(), name='group-update'),
    path('edit/<slug:slug>/', PublisherUpdate.as_view(), name='update'),
    path('detail/<slug:slug>/', PublisherDetail.as_view(), name='detail'),
    path('new/', PublisherCreate.as_view(), name='create'),
    path('delete/<str:pk>/', PublisherDelete.as_view(), name='delete')
]

congregationms/reports/urls.py
from django.urls import path

from .views import (
    InfirmedListView, MFSCreate, MFSDelete, MFSDetail, MFSList, MFSUpdate,
    MFSHistoryList, PioneerListView, sample_mfs, ServantListView,
    ShareToRedirectView, InactivePublisherListView, AssetListView
)

app_name = 'reports'
urlpatterns = [
    path('monthly-field-service/', MFSList.as_view(), name='mfs-index'),
    path('monthly-field-service/history/publisher/<slug:publisher>/',
         MFSHistoryList.as_view(), {'view_type': 'publisher'},
         name='mfs-history'),
    path('monthly-field-service/history/group/<str:group>/',
         MFSHistoryList.as_view(), {'view_type': 'group'},
         name='mfs-history-group'),
    path('monthly-field-service/delete/<str:pk>/',
         MFSDelete.as_view(), name='mfs-delete'),
    path('monthly-field-service/new/', MFSCreate.as_view(), name='mfs-create'),
    path('monthly-field-service/<str:pk>/',
         MFSDetail.as_view(), name='mfs-detail'),
    path('monthly-field-service/update/<str:pk>/',
         MFSUpdate.as_view(), name='mfs-update'),


    path('mfs/download/group/<str:pk>/', sample_mfs, name='mfs-download'),
    path('mfs/<str:publisher>/share-to/',
         ShareToRedirectView.as_view(), name='share_to'),

    path(
        'publishers/inactive/',
        InactivePublisherListView.as_view(),
        name='publishers_inactive'),
    path(
        'publishers/assets/',
        AssetListView.as_view(),
        name='publishers_assets'
    ),
    path(
        'publishers/<str:view_type>/',
        InfirmedListView.as_view(),
        name='publishers'),

    path(
        'pioneering/<str:view_type>/',
        PioneerListView.as_view(),
        name='pioneering'),

    path(
        'servants/<str:view_type>/',
        ServantListView.as_view(),
        name='servants'),
]

congregationms/system/urls.py
from django.urls import path

from .views import dashboard, AccountView

app_name = 'system'
urlpatterns = [
    path('dashboard', dashboard, name='dashboard'),
    path('account/', AccountView.as_view(), name='account'),
]

congregationms/urls.py
from django.contrib import admin
from django.urls import path

from system.views import home

urlpatterns = [
    path('', home, name='home'),
    path('admin/', admin.site.urls),
]

congregationms/cities/models.py
from django.db import models


class Country(models.Model):
    name = models.CharField(max_length=100)
    symbol = models.CharField(max_length=10, unique=True)

    class Meta:
        ordering = 'name',

    def __str__(self):
        return self.name


class State(models.Model):
    name = models.CharField(max_length=100)
    symbol = models.CharField(max_length=10)
    import_code = models.CharField(max_length=10, blank=True)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)

    class Meta:
        ordering = 'country__name', 'name'

    def __str__(self):
        return self.name


class City(models.Model):
    name = models.CharField(max_length=100)
    symbol = models.CharField(max_length=10)
    state = models.ForeignKey(State, on_delete=models.CASCADE)

    class Meta:
        ordering = 'state__name', 'name'

    def __str__(self):
        return self.name

congregationms/cities/views.py
from django.shortcuts import render

# Create your views here.

congregationms/mailing/views.py
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import reverse
from django.views.generic.edit import CreateView

from .forms import MailModelForm
from .models import Mail


class MailCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    """Receive query params [filename]."""
    form_class = MailModelForm
    model = Mail
    permission_required = ('mailing.add_mail',)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_initial(self):
        initial = super().get_initial()
        initial = initial.copy()
        initial['attachment'] = self.request.GET.get('filename')
        return initial

    def get_success_url(self, *args, **kwargs):
        return reverse('publishers:index')

    def form_valid(self, form):
        _value = super().form_valid(form)

        if form.send_email():
            messages.success(
                self.request,
                'Successfully shared via email!')
        else:
            message = 'Something went wrong. Unable to share via \
                        email. Please check your internet connection.'
            messages.error(self.request, message)
            return HttpResponseRedirect(self.request.GET.get('on_fail'))
        return _value

congregationms/pioneering/views.py
from django.contrib import messages
from django.db import transaction
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .forms import PioneerDetailFormSet, PioneerModelForm
from .models import Pioneer
from publishers.utils import get_user_groups_members
from system.utils import (
    LoginAndPermissionRequiredMixin, AddUserToFormMixin, AddRequestToForm)


class PioneerListView(LoginAndPermissionRequiredMixin, ListView):
    model = Pioneer
    context_object_name = 'pioneers'
    permission_required = ('pioneering.view_pioneer',)

    def get_queryset(self):
        auth_pubs = self.request.authorized_publisher_pks
        if auth_pubs:
            queryset = Pioneer.objects.filter(publisher__in=auth_pubs)
            queryset = queryset.select_related('publisher')
        else:
            queryset = self.model.objects.none()

        return queryset


class PioneerDetailView(LoginAndPermissionRequiredMixin, DetailView):
    model = Pioneer
    context_object_name = 'pioneer'
    slug_field = 'code'
    permission_required = ('pioneering.view_pioneer',)

    def get_queryset(self):
        q = super().get_queryset()
        q = q.prefetch_related('details', 'publisher')
        return q


class PioneerCreateView(
        AddRequestToForm, LoginAndPermissionRequiredMixin, CreateView):
    model = Pioneer
    form_class = PioneerModelForm
    permission_required = ('pioneering.add_pioneer',)

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data['details'] = PioneerDetailFormSet(self.request.POST)
        else:
            data['details'] = PioneerDetailFormSet()

        return data

    def form_valid(self, form):
        context = self.get_context_data()
        details = context['details']

        with transaction.atomic():
            if details.is_valid():
                self.object = form.save()
                details.instance = self.object
                details.save()

        messages.success(
            self.request,
            'Successfully created new pioneer. Continue editing other details'
        )
        return super().form_valid(form)

    def get_success_url(self, *args, **kwargs):
        return reverse('pioneering:update', args=[str(self.object.code)])


class PioneerUpdateView(
        AddRequestToForm, LoginAndPermissionRequiredMixin, UpdateView):
    model = Pioneer
    form_class = PioneerModelForm
    context_object_name = 'pioneer'
    slug_field = 'code'
    permission_required = ('pioneering.change_pioneer',)

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data['details'] = PioneerDetailFormSet(
                self.request.POST, instance=self.object)
        else:
            data['details'] = PioneerDetailFormSet(instance=self.object)
        data['is_active'] = self.object.is_active
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        details = context['details']

        with transaction.atomic():
            if details.is_valid():
                details.instance = self.object
                details.save()
                self.object = form.save()

        messages.success(
            self.request,
            'Successfully updated.'
        )
        return super().form_valid(form)


class PioneerDeleteView(LoginAndPermissionRequiredMixin, DeleteView):
    model = Pioneer
    success_url = reverse_lazy('pioneering:index')
    permission_required = ('pioneering.delete_pioneer',)

    def get_success_url(self):
        messages.success(
            self.request,
            'Successfully deleted {}.'.format(str(self.object))
        )
        return super().get_success_url()

congregationms/publishers/views.py
#from django.shortcuts import render
from django.contrib import messages
from django.db import transaction
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .forms import GroupModelForm, GroupMemberFormSet, PublisherModelForm
from .models import Group, Publisher, Member
from .utils import get_publishers_as_choices
from system.utils import LoginAndPermissionRequiredMixin


# Create your views here.
class PublisherList(LoginAndPermissionRequiredMixin, ListView):
    model = Publisher
    permission_required = 'publishers.view_publisher',

    def get_queryset(self):
        auth_pubs = self.request.authorized_publisher_pks
        if auth_pubs:
            queryset = Publisher.objects.filter(id__in=auth_pubs)
        else:
            queryset = self.model.objects.none()

        return queryset


class PublisherUpdate(LoginAndPermissionRequiredMixin, UpdateView):
    model = Publisher
    form_class = PublisherModelForm
    context_object_name = 'publisher'
    permission_required = 'publishers.change_publisher',

    def get_queryset(self, **kwargs):
        queryset = super().get_queryset(**kwargs)
        queryset = queryset.select_related('city', 'city__state')

        return queryset

    def form_valid(self, form):
        messages.success(
            self.request,
            'Successfully updated.'
        )
        return super().form_valid(form)


class PublisherDetail(LoginAndPermissionRequiredMixin, DetailView):
    model = Publisher
    context_object_name = 'publisher'
    permission_required = 'publishers.view_publisher',

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        contact_numbers = self.object.contact_numbers
        contact_numbers = contact_numbers.split(',')
        contact_numbers = ', '.join(contact_numbers)

        context['contact_numbers'] = contact_numbers
        return context

    def get_queryset(self, **kwargs):
        queryset = super().get_queryset(**kwargs)
        queryset = queryset.select_related(
            'city', 'city__state', 'city__state__country')

        return queryset


class PublisherCreate(LoginAndPermissionRequiredMixin, CreateView):
    model = Publisher
    form_class = PublisherModelForm
    permission_required = 'publishers.add_publisher',

    def form_valid(self, form):
        messages.success(
            self.request,
            'Successfully created new publisher. Continue editing other details'
        )
        return super().form_valid(form)

    def get_success_url(self, *args, **kwargs):
        return reverse('publishers:update', args=[str(self.object.slug)])


class PublisherDelete(LoginAndPermissionRequiredMixin, DeleteView):
    model = Publisher
    success_url = reverse_lazy('publishers:index')
    permission_required = 'publishers.delete_publisher',

    def get_success_url(self):
        messages.success(
            self.request,
            'Successfully deleted {}.'.format(str(self.object))
        )
        return super().get_success_url()


class GroupList(LoginAndPermissionRequiredMixin, ListView):
    model = Group
    permission_required = 'publishers.view_group',

    def get_queryset(self):
        queryset = self.model.objects.none()

        # user = self.request.user
        # publisher = user.publisher
        # group = publisher.group_members.filter(is_active=True)
        # group = group.first()  # publishers.Member object
        # if group:
        #     queryset = super().get_queryset()
        #     queryset = queryset.filter(id=group.group_id)
        groups = self.request.authorized_groups  # publisher.UserGroup objects
        if groups:
            groups = [g.group_id for g in groups]  # Group pks
            queryset = super().get_queryset().filter(id__in=groups)
            queryset = queryset.select_related('congregation')

        return queryset


class GroupDetail(LoginAndPermissionRequiredMixin, DetailView):
    model = Group
    context_object_name = 'group'
    permission_required = 'publishers.view_group',


class GroupUpdate(LoginAndPermissionRequiredMixin, UpdateView):
    model = Group
    form_class = GroupModelForm
    context_object_name = 'group'
    permission_required = 'publishers.change_group',

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            formset = GroupMemberFormSet(
                self.request.POST, instance=self.object)
        else:
            formset = GroupMemberFormSet(instance=self.object)

        data['members'] = formset
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        members = context['members']

        with transaction.atomic():
            self.object = form.save()
            if members.is_valid():
                members.instance = self.object
                members.save()

        messages.success(
            self.request,
            'Successfully edited Group {}.'.format(str(self.object))
        )
        return super().form_valid(form)


class GroupDelete(LoginAndPermissionRequiredMixin, DeleteView):
    model = Group
    success_url = reverse_lazy('publishers:group-index')
    permission_required = 'publishers.delete_group',

    def get_success_url(self):
        messages.success(
            self.request,
            'Successfully deleted {}.'.format(str(self.object))
        )
        return super().get_success_url()


class GroupCreate(LoginAndPermissionRequiredMixin, CreateView):
    model = Group
    form_class = GroupModelForm
    permission_required = 'publishers.add_group',

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            formset = GroupMemberFormSet(self.request.POST)
        else:
            formset = GroupMemberFormSet()

        data['members'] = formset

        return data

    def form_valid(self, form):
        context = self.get_context_data()
        members = context['members']

        with transaction.atomic():
            self.object = form.save()
            if members.is_valid():
                members.instance = self.object
                members.save()

        messages.success(
            self.request,
            'Successfully created new Group {}.'.format(str(self.object))
        )
        return super().form_valid(form)

congregationms/templates/reports/base.html
{% extends "base.html" %}


{% block breadcrumbs %}
  <li><a href='#'>Reports</a></li>
  {% block subbreadcrumbs %}{% endblock subbreadcrumbs %}
{% endblock breadcrumbs %}

{% block navbaritems %}
  {% include "_snippets/navbar_items.html" with mfs_active='is-active' %}
{% endblock navbaritems %}

{% block aside_menu %}
  {% include "aside.html" with mfs_active='is-active' %}  
{% endblock aside_menu %}

{% block main %}
<div class="content">
  {% block content %}{% endblock content %}  
</div>
{% endblock main %}

congregationms/templates/reports/mfs_history.html
{% extends "reports/base.html" %}

{% block title %}
	{% if publisher %}
  	<title>Monthly Field Service - Publisher History | {{publisher|title}}</title>  
	{% endif %}
	{% if group %}
  	<title>Monthly Field Service - Group History | {{group|title}}</title>  
	{% endif %}
{% endblock title %}

{% block subbreadcrumbs %}
  <li><a href='{% url "reports:mfs-index" %}'>Monthly Field Service</a></li>
	{% if publisher %}
		<li><a href="#">{{publisher.name|title}}</a></li>
	{% endif %}
	{% if group %}
		<li><a href="#">By group</a></li>
		<li><a href="#">{{group|title}}</a></li>
	{% endif %}

  <li class="is-active"><a href='#'>History</a></li>
{% endblock subbreadcrumbs %}

{% block content %}
	<div id="app">
		{% if  publisher %}
			<h1>Monthly Field Service - Publisher History</h1>
			<a :href="'{% url 'reports:share_to' publisher.pk %}?from=' + from + '&to=' + to">
				<button class="button is-pulled-right is-info"><span class="icon"><i class="fas fa-share"></i></span><span>Share</span></button>
			</a>
		{% endif %}
		{% if group %}
			<h1>Monthly Field Service - Group History</h1>
		{% endif %}

		{% if  publisher %}
			<p><span class="is-size-3">{{publisher.name|title}}</span> {% include "publishers/snippets/iconlinkedtopublisher.html" %}</p>
		{% endif %}
		{% if group %}
			<p><a href="{% url 'publishers:group-detail' group.pk %}" title="View Group detail."><span class="is-size-3">{{group|title}}</span></a></p>
		{% endif %}

		<form>
		    <div class="field is-horizontal">
		      <div class="field-body">
			      <div class="field">
		        <label class="label">From</label>
				      <div class="control">
				      	<input class="input" type="month" name="from" v-model="from">
				      </div>
			      </div>
		      	
			    <div class="field">
		        <label class="label">To</label>
			      <div class="control">
			      	<input class="input" type="month" name="to" v-model="to">
			      </div>
			    </div>

			    <div class="field">
			      <div class="control">
			      	<input type="submit" class="button is-outlined is-info" value="Search">
			      </div>
			    </div>
		      </div>
		    </div>
		</form>
		<table class="table is-bordered is-hoverable is-fullwidth ">
			<thead>
				<tr>
					<th class="has-text-centered">Month</th>
					{% if group %}<th>Publisher</th>{% endif %}
					<th class="has-text-centered" title="Placements">P</th>
					<th class="has-text-centered" title="Video Showings">VS</th>
					<th class="has-text-centered">Hours</th>
					<th class="has-text-centered" title="Return Visits">RV</th>
					<th class="has-text-centered" title="Bible Studies">BS</th>
					<th class="has-text-centered">Comments</th>
				</tr>
			</thead>
			<tbody>
				{% for report in  reports %}
				<tr @click="goTo('{% url 'reports:mfs-detail' report.pk %}')">
					<td class="has-text-centered"><u class="has-text-link">{{report.month_ending|date:'M-Y'}}</u></td>
					{% if group %}<td>{{report.publisher|title}}</td>{% endif %}
					<td class="has-text-centered">{{report.placements}}</td>
					<td class="has-text-centered">{{report.video_showing}}</td>
					<td class="has-text-centered">{{report.hours}}</td>
					<td class="has-text-centered">{{report.return_visits}}</td>
					<td class="has-text-centered">{{report.bible_study}}</td>
					<td>{{report.comments}}</td>
				</tr>
				{% endfor %}
				{% if reports %}
					<tr>
						<td class="has-text-centered" {% if group %}colspan=2{% endif %}>***TOTALS***</td>
						<td class="has-text-centered">{{totals.placements__sum}}</td>
						<td class="has-text-centered">{{totals.video_showing__sum}}</td>
						<td class="has-text-centered">{{totals.hours__sum}}</td>
						<td class="has-text-centered">{{totals.return_visits__sum}}</td>
						<td class="has-text-centered">{{totals.bible_study__sum}}</td>
						<td></td>
					</tr>
					<tr>
						<td class="has-text-centered" {% if group %}colspan=2{% endif %}>Auxillary Pioneer</td>
						<td class="has-text-centered">{{totals.au_placements|default:0}}</td>
						<td class="has-text-centered">{{totals.au_video_showing|default:0}}</td>
						<td class="has-text-centered">{{totals.au_hours|default:0}}</td>
						<td class="has-text-centered">{{totals.au_return_visits|default:0}}</td>
						<td class="has-text-centered">{{totals.au_bible_study|default:0}}</td>
						<td></td>
					</tr>
					<tr>
						<td class="has-text-centered" {% if group %}colspan=2{% endif %}>Regular Pioneer</td>
						<td class="has-text-centered">{{totals.rp_placements|default:0}}</td>
						<td class="has-text-centered">{{totals.rp_video_showing|default:0}}</td>
						<td class="has-text-centered">{{totals.rp_hours|default:0}}</td>
						<td class="has-text-centered">{{totals.rp_return_visits|default:0}}</td>
						<td class="has-text-centered">{{totals.rp_bible_study|default:0}}</td>
						<td></td>
					</tr>
					<tr>
						<td class="has-text-centered" {% if group %}colspan=2{% endif %}>Special Pioneer</td>
						<td class="has-text-centered">{{totals.sp_placements|default:0}}</td>
						<td class="has-text-centered">{{totals.sp_video_showing|default:0}}</td>
						<td class="has-text-centered">{{totals.sp_hours|default:0}}</td>
						<td class="has-text-centered">{{totals.sp_return_visits|default:0}}</td>
						<td class="has-text-centered">{{totals.sp_bible_study|default:0}}</td>
						<td></td>
					</tr>
				{% else %}
					
				{% endif %}
				{% if not reports %}
				<tr>
					{% if group %}
						<td class="has-text-centered" colspan=8>No data available.</td>	
					{% else %}
						<td class="has-text-centered" colspan=7>No data available.</td>
					{% endif %}
				</tr>	
				{% endif %}
			</tbody>
		</table>

		{% if group %}
			<a :href="'{% url 'reports:mfs-download' group.pk %}?from=' + from + '&to=' + to"><button class="button is-outlined is-pulled-right">Export as Document</button></a>
			
		{% endif %}
	</div>
{% endblock content %}

{% block vueinstance %}
  <script>
    vueinstance = new Vue({
      el: '#app',
      delimiters: ['[[', ']]'],
      data: () => ({
        from: '{{from}}',
        to: '{{to}}'
      }),
      methods: {
      	goTo: function (url) {
      		window.location.href = url;
      	}
      }
    });
  </script>
{% endblock vueinstance %}

congregationms/templates/reports/monthlyfieldservice_detail.html
{% extends "reports/base.html" %}
{% load static %}

{% block title %}
  <title>Monthly Field Service Detail | {{report.publisher|title}} for {{report.month_ending|date:'M-Y'}}</title>
{% endblock title %}

{% block subbreadcrumbs %}
  <li><a href='{% url "reports:mfs-index" %}'>Monthly Field Service</a></li>
  <li class="is-active"><a href='#'>Detail</a></li>  
{% endblock subbreadcrumbs %}

{% block content %}
  <h1>Monthly Field Service Report</h1>
  
  <div class="field is-grouped is-pulled-right">

    <div class="control" id="delete-button-app">
      <form id="form--{{ report.pk }}" action='{% url "reports:mfs-delete" report.pk %}' method="POST" @submit.prevent="confirmDelete">
        {% csrf_token %}
        <button class="button is-outlined" type="submit" form="form--{{ report.pk }}" :disabled="disabled">{% include "_snippets/icon_trash.html" %}</button>
      </form>
    </div>

    <div class="control">
      <a href='{% url "reports:mfs-update" report.pk %}'><button class="button is-outlined">{% include "_snippets/icon_edit.html" %}</button></a>
    </div>
  </div>
  
  <p><span class="is-size-3">{{ report.publisher|title }}</span> {% include "publishers/snippets/iconlinkedtopublisher.html" with publisher=report.publisher %}</p>
  <p><a href='{% url "reports:mfs-history" publisher_slug %}'>View history</a></p>

  <table class="table">
    <tbody>
      <tr>
        <th>Month</th>
        <td><strong>{{ report.month_ending|date:'M-Y' }}</strong></td>
      </tr>

      <tr>
        <th>Placements</th>
        <td>{{ report.placements }}</td>
      </tr>

      <tr>
        <th>Video Showings</th>
        <td>{{ report.video_showing }}</td>
      </tr>
      
      <tr>
        <th>Hours</th>
        <td>{{ report.hours }}</td>
      </tr>
      
      <tr>
        <th>Return Visits</th>
        <td>{{ report.return_visits }}</td>
      </tr>
      
      <tr>
        <th>Bible Studies</th>
        <td>{{ report.bible_study }}</td>
      </tr>
      
      <tr>
        <th>Comments</th>
        <td>{{ report.comments }}</td>
      </tr>

      <tr>
        <th>Pioneer</th>
        <td>
          <span class="icon">
            {% if pioneering %}
              <i class="fas fa-check has-text-success"></i>
              {{pioneering}}
            {% else %}
              <i class="fas fa-times has-text-danger"></i>
            {% endif %}
          </span>
        </td>
      </tr>
      
    </tbody>
  </table>
{% endblock content %}

{% block vueinstance %}
    <script src="{% static "deleteButtonApp.js" %}"></script>
{% endblock vueinstance %}

congregationms/templates/reports/monthlyfieldservice_list.html
{% extends "reports/base.html" %}

{% block title %}
  <title>Monthly Field Service - List</title>  
{% endblock title %}

{% block subbreadcrumbs %}
  <li><a href='{% url "reports:mfs-index" %}'>Monthly Field Service</a></li>
  <li class="is-active"><a href='#'>List</a></li>
{% endblock subbreadcrumbs %}

{% block content %}
  <h1>Monthly Field Service</h1>

  <div class="field is-pulled-right">
    <div class="control">
      <a href='{% url "reports:mfs-create" %}'>{% include "_snippets/button_new.html" with new_button_title='Create new record' %}</a>
    </div>
  </div>

  <form>
    <div class="field is-horizontal">
      <div class="field-label is-normal">
        <label class="label">Month/Year:</label>
      </div>
      <div class="field-body">
        <div class="field">
          <div class="control">
              <input class="input" type="month" name="monthyear" value="{{monthyear}}">
          </div>
        </div>
        <div class="field">
          <div class="control">
              <input class="button is-info is-outlined" type="submit" value="search">
          </div>
        </div>
      </div>
    </div>
  </form>
  <table class="table is-fullwidth">
    <thead>
      <tr>
        <th>Name</th>
        <th>Group</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for report in object_list %}
          <tr>
            <td>
              {{ report.publisher|title }} {% if report.pioneering %}({{report.pioneering.pioneer_type}}){% endif %}
            </td>
            <td><a href="{% url 'publishers:group-detail' report.group.pk %}" title="View group detail">{{ report.group.name }}</a></td>
            <td>
              <a href='{% url "reports:mfs-detail" report.pk %}'><span class="button is-outlined">{% include "_snippets/icon_view.html" %}</span></a>
              <a href='{% url "reports:mfs-update" report.pk %}'><span class="button is-outlined">{% include "_snippets/icon_edit.html" %}</span></a>
            </td>
          </tr>
      {% endfor %}

    {% if not object_list %}
      <tr>
        <td colspan="3" class="has-text-centered">No data. Please <a href="{% url 'reports:mfs-create' %}"><u>add</u></a>.</td>
      </tr>  
    {% endif %}
    </tbody>
  </table>
{% endblock content %}

{% block vueinstance %}
  <script>
    vueinstance = new Vue({
      el: '#app',
      delimiters: ['[[', ']]'],
      data: () => ({
        
      })
    });
  </script>
{% endblock vueinstance %}